name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 17
      - name: Install sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt
      - name: Generate JAR
        run: sbt assembly
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files:
            ttr-scala.jar