name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 17
      - name: Install sbt
        uses: coursier/setup-action@v1
      - name: Generate JAR
        run: sbt assembly
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files:
            ttr-scala.jar